"""Add trust_score

Revision ID: 63ff2cb59cff
Revises: 830a3728d03b
Create Date: 2026-06-06 18:23:35.534233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ff2cb59cff'
down_revision: Union[str, Sequence[str], None] = '830a3728d03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('trust_score', sa.Integer(), server_default='100', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'trust_score')
    # ### end Alembic commands ###
