"""Add hashed_api_key

Revision ID: ba8706f9743f
Revises: 63ff2cb59cff
Create Date: 2026-06-06 18:35:34.287956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8706f9743f'
down_revision: Union[str, Sequence[str], None] = '63ff2cb59cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('hashed_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'hashed_api_key')
    # ### end Alembic commands ###
