"""Add WorkflowCheckpoint

Revision ID: d780138d9903
Revises: ba8706f9743f
Create Date: 2026-06-06 20:11:24.504639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd780138d9903'
down_revision: Union[str, Sequence[str], None] = 'ba8706f9743f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('agent_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_checkpoints_id'), 'workflow_checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_checkpoints_workflow_run_id'), 'workflow_checkpoints', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_checkpoints_workflow_run_id'), table_name='workflow_checkpoints')
    op.drop_index(op.f('ix_workflow_checkpoints_id'), table_name='workflow_checkpoints')
    op.drop_table('workflow_checkpoints')
    # ### end Alembic commands ###
